name: Vite Build

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd admin_frontend
          npm install
          npm run build
          cd ../
          cd client_frontend
          npm install
          npm run build
          rm -rf admin_frontend
          rm -rf client_frontend
          rm .gitignore
          rm -rf .vscode
          rm -rf .github
          rm -rf .git
          rm README.MD

      - name: Zip project
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r code.zip .

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: Release v${{ github.run_number }}
          tag: stable-release
          body: Release v${{ github.run_number }}
          artifacts: "code.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          makeLatest: true
